services:
  satis:
    restart: unless-stopped
    build:
      context: .
      args:
        # Use environment variables with fallback to default values
        USER_ID: ${USER_ID:-1000}
        GROUP_ID: ${GROUP_ID:-1000}
    ports:
      - "${PORT:-9000}:8080"
    volumes:
      - ./repos:/repos
      - ./satis:/build
